In [1]:
import numpy as np
import scipy.io as sio
import cv2
image=cv2.imread("C:/Users/Mason/desktop/styles/woman.jpg")
image_t=image.transpose(2,1,0)
print (image)

[[[204 219 211]
  [162 177 169]
  [181 196 188]
  ..., 
  [186 209 241]
  [185 208 240]
  [186 209 241]]

 [[175 190 182]
  [121 136 128]
  [126 141 133]
  ..., 
  [167 190 222]
  [167 190 222]
  [171 194 226]]

 [[179 194 186]
  [116 131 123]
  [113 128 120]
  ..., 
  [158 181 213]
  [160 183 215]
  [165 188 220]]

 ..., 
 [[255 251 251]
  [255 254 254]
  [255 254 250]
  ..., 
  [120  96 126]
  [111  87 117]
  [117  95 124]]

 [[255 252 252]
  [255 254 254]
  [255 254 250]
  ..., 
  [133 112 144]
  [128 110 141]
  [128 110 141]]

 [[255 252 252]
  [255 254 254]
  [255 253 249]
  ..., 
  [153 136 169]
  [149 134 166]
  [140 125 157]]]


In [2]:
import numpy as np
import scipy.io as sio
import cv2
image=cv2.imread("C:/Users/Mason/desktop/styles/woman.jpg")
image_t=image.transpose(2,1,0)
print(image_t)

[[[204 175 179 ..., 255 255 255]
  [162 121 116 ..., 255 255 255]
  [181 126 113 ..., 255 255 255]
  ..., 
  [186 167 158 ..., 120 133 153]
  [185 167 160 ..., 111 128 149]
  [186 171 165 ..., 117 128 140]]

 [[219 190 194 ..., 251 252 252]
  [177 136 131 ..., 254 254 254]
  [196 141 128 ..., 254 254 253]
  ..., 
  [209 190 181 ...,  96 112 136]
  [208 190 183 ...,  87 110 134]
  [209 194 188 ...,  95 110 125]]

 [[211 182 186 ..., 251 252 252]
  [169 128 123 ..., 254 254 254]
  [188 133 120 ..., 250 250 249]
  ..., 
  [241 222 213 ..., 126 144 169]
  [240 222 215 ..., 117 141 166]
  [241 226 220 ..., 124 141 157]]]
